[general]
    tags = ["warn", "sarif"]
    description = "Test warnings discovered by diKTat, reading expected warnings from SARIF file"
    suiteName = "Only Warnings: with SARIF format"
    expectedWarningsPattern = "// ;warn:?(.*):(\\d+):? ?(.+)?"
    execCmd = "./run_save.sh EASY01.c && echo"
    timeOutMillis = 60000

[warn]
    #execFlags = "--reporter=sarif"
    # regular expression to detect tests
    testNameRegex = ".*EASY01.c"
    actualWarningsFormat = "SARIF"
    # by default, in SARIF mode, it's supposed, that tool will print sarif report into the stdout
    # however, it also could be provided via file
    actualWarningsFileName = "report.sarif"
    fileNameCaptureGroupOut = 1
    lineCaptureGroupOut = 2
    columnCaptureGroupOut = 3
    messageCaptureGroupOut = 4
    exactWarningsMatch = false
    warningTextHasColumn = true
    warningTextHasLine = true

